version: '3.7'

services:
  server:
    build:
      context: .
      target: final
    restart: unless-stopped
    network_mode: host
    ports:
      - "8080:8080"
      - "4433:4433"
    env_file: server.env
    secrets:
      - database_url
      - localhost_crt
      - localhost_key
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d \"$(cat /run/secrets/postgres_db)\" -U \"$(cat /run/secrets/postgres_user)\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  postgres_db:
    file: secrets/POSTGRES_DB.txt
  postgres_user:
    file: secrets/POSTGRES_USER.txt
  postgres_password:
    file: secrets/POSTGRES_PASSWORD.txt
  database_url:
    file: secrets/DATABASE_URL.txt
  localhost_crt:
    file: secrets/localhost.crt
  localhost_key:
    file: secrets/localhost.key
